### ISSUE TITLE
No bug, just info

### ISSUE THREAD

**Issue by thunderstar5000** [LibreDMR/OpenGD77_UserGuide#11]
Hi there,

reading your documentation I missed one point, that I found not described.

Device: GD-77
Changing VFO from A to B is done by pressing the orange button, then change from A to B.

----
It is much easier: long press red key changes from VFO A to B.

----
One thing, the doc also did not tell:

If using dual watch and one of the VFOs is set to DMR and the other to FM, does it switch between FM and DMR? 
Could not verify this,m as I got no second transceiver, but maybe you know.

Best regards

Hans

**Comment by rogerclarkmelbourne** [comment]
The doc does need to be updated.

Re: VFO dual watch

VFO A and B are just Channels with special names and displayed differently etc

So if you have one VFO as DMR and the other as FM thats how the radio will function. 
It won't change the mode settings of either VFO A or B in dual watch
