### ISSUE TITLE
Swapping DMR/FM modes

### ISSUE THREAD

**Issue by DustyLoon** [LibreDMR/OpenGD77_UserGuide#78]
The manual states:

https://github.com/LibreDMR/OpenGD77_UserGuide/blob/master/OpenGD77_User_Guide.md#changing-between-fm-mode-and-dmr-mode

`Changing between FM mode and DMR mode
Press the SK1 + Star keys to toggle between FM and DMR mode, on either the VFO or Channel screens.`

However on both my GD-77 and TYT-9600, the key combination appears to be SK2 + Star (or P1 + Star on the 9600).

I'm still attempting to determine if I am misunderstanding the documentation or if I inadvertently made a change on my radios that is causing them to act differently from the documentation. So far I'm not finding anything.

**Comment by rogerclarkmelbourne** [comment]
You are correct. This is a typo

It should be SK2 + Star (*)  to change mode 

P1 on MD9600 is mapped to SK2

**Comment by rogerclarkmelbourne** [comment]
Thanks

Note. I can't renegerate the PDF version immediately. PDF creation has to run on a Linux box and I don't have one running at the moment
