### ISSUE TITLE
cant join the forum

### ISSUE THREAD

**Issue by stevefoxuk** [LibreDMR/OpenGD77_UserGuide#84]
You wont allow people to join the forum without a call sign and ignore registrations without one.

Since I found this out and realised that was why my registration had been ignored, I emailed the admin to assure that im not a Bot (just an excuse IMO) but my emails go totally ignored.

Its this sort of thing that give hams the reputation of being hostile to those outside their circle.

**Comment by ih8ms** [comment]
I totally can understand that you don't want bots in your forum.

However, I find the requirement to be a licensed ham radio operator quite odd I must say. Espechially when there is no requirement for a license if you just listen. So, until I have my license, I'm not allowed to join this forum? Really?

I mean sure, do whatever you like. I'm not entitled to anything and you can configure your forum any way you want, but I now get what @stevefoxuk is saying about "being hostile".

Regardless, here's what I'm gonna do: I will randomly search for a call sign that somehow matches my email address and do a regestration with that. The forum moderator will be none the wiser and I get a working forum login out of it. When I finally have my own call sign, I'll do another registration and delete(?) the old one. Let's just hope the poor bloke that I'll steal the call sign from doesn't want to use the forum as well until then.

Or maybe I find someone who already has a login (not too unlikely) and I'll simply ask them to share.

That said, I hope that @rogerclarkmelbourne re-evaluates the current subscription policy.
