### ISSUE TITLE
GPS lock notification sound

### ISSUE THREAD

**Issue by mrbaloghakos** [LibreDMR/OpenGD77_UserGuide#97]
The RT3S is famous for its bad quality GPS and long lock time. It would be nice to get a notification sound when the GPS has a lock, this way it would be not necessary to check the screen constantly, waiting for a lock.

**Comment by f1rmb** [comment]
If you're in the GPS menu, there is a Beep (unless you have voice prompt enabled).
In other screens, there is no point to introduce a beep for this, it would just be noise and confusing.

This is not the place for this, a forum exists: [opengd77.com](https://www.opengd77.com/)
